### ISSUE TITLE
Dum Drums MIDI cannot be mapped below C3.

### ISSUE THREAD

**Issue by da-Jester** [JoepVanlier/JSFX#101]
I have a MIDI keyboard with 16 drum pads, and by default they are mapped C2-E3. The lowest note that I can assign Dum Drums drum sounds to is a C3. There is a possible workaround for me, but I am wondering why you can't assign the drums to any notes lower than C2. Again, this is not at all pressing, and I may be missing something, but it would be nice if the range that you could map the sounds to was larger/had lower notes in it.

**Comment by JoepVanlier** [comment]
Good point! I tried to pick a range that would cover a fair number of octaves, but I might have chosen a bit poorly. I have updated the base octave (lowest note shown on the little keyboard) to be one octave lower, and allow customization of the base octave shown on the keyboard now.

Hope that helps! Thanks for the heads up!

**Comment by da-Jester** [comment]
Thank you so much, it works great!
