### ISSUE TITLE
Octave Mode Midi Fix

### ISSUE THREAD

**Issue by camerongillette** [JoepVanlier/JSFX#107]
Hey there, I love your work, thank you so much. I found a tiny bug and here's the code to fix it.

On the final boss plugin, line 33 needs to be updated because as is, it can't select the different octave modes.

`slider14:octaver_mode=0<0,5,1>-Octave mode`

I tried to make a pr, but I would need write permissions. Anyway, hope this was helpful, thank you again for your amazing work.

-BABYWOLF

**Comment by JoepVanlier** [comment]
> Hey there, I love your work, thank you so much. I found a tiny bug and here's the code to fix it.
> 
> On the final boss plugin, line 33 needs to be updated because as is, it can't select the different octave modes.
> 
> `slider14:octaver_mode=0<0,5,1>-Octave mode`

Good catch! Merged in version [0.09](https://github.com/JoepVanlier/JSFX/commit/3b4423e61c9a074e9e851d2c2145f051e71e9fac).

> I tried to make a pr, but I would need write permissions.

Ah yeah, that's pretty typical. For future reference, normally the workflow is to make a fork, make the changes there and then you can do a pull request upstream. This works too though and in some cases is faster!

> Anyway, hope this was helpful, thank you again for your amazing work.

It is! Thanks for contributing!
