### ISSUE TITLE
[feature] Amaranth: I'd love to see an independent grain rate knob 

### ISSUE THREAD

**Issue by autotel** [JoepVanlier/JSFX#110]
First off, thank you so much for all these plugins, they're all so good sounding and fun to use! I can't wrap my head around on how you managed to create them! hats off.

Here the feature request: The amount of grains triggered per second are a product of "overlap" and "size". However, I've found myself wanting to slide up the grains per second without increasing overlap or decreasing size. A dedicated rate knob might allow some additional expressions with Amaranth.

**Comment by JoepVanlier** [comment]
Hey, that's kind of what the tiny toggle next to overlap does. When you select that it switches to an absolute distance between firing grains.

![toggle](https://github.com/JoepVanlier/JSFX/assets/19836026/84e46f93-fb18-4093-bfb6-a36a3d1dc229)

The issue with this mode is the reason I initially went with overlap / size, which is that you run out of grains relatively quickly.

That said, I could see if I can optionally bump the grain count a bit.

**Comment by JoepVanlier** [comment]
I just pushed a version that allows a much higher grain count (4 times as much). Note that it relies on a newer version of reaper though (since I used the JSFX preprocessor).

**Comment by autotel** [comment]
amazing! thanks for checking it :)
