### ISSUE TITLE
dB levels at cursor don't match axis ticks

### ISSUE THREAD

**Issue by endolith** [JoepVanlier/JSFX#2]
This one is about right (-144 dB):

![-144](https://user-images.githubusercontent.com/58611/43905597-5bb34eb2-9bbf-11e8-80ae-f3bef940c25f.png)

But these are not:

-12 dB
![-12](https://user-images.githubusercontent.com/58611/43905604-61d41f2e-9bbf-11e8-9978-c95379887cac.png)

-72 dB
![-72](https://user-images.githubusercontent.com/58611/43905605-61e399c2-9bbf-11e8-8aaf-9ee4b9614f4b.png)

**Comment by JoepVanlier** [comment]
Thanks for the bug report! 

Should be fixed in 4381c5939eecc6dc4cf0efe94da961dded5a85b1

Please reopen the issue if you find any further problems :)
