### ISSUE TITLE
Question: why Filther is changing phase when no filter is enabled?

### ISSUE THREAD

**Issue by veksha** [JoepVanlier/JSFX#24]
why Filther is changing phase of a signal when there are no filters enabled?
[https://imgur.com/a/pcYzchm](https://imgur.com/a/pcYzchm)

**Comment by JoepVanlier** [comment]
Hello!

Filther 3.09 (released in 0617b12d34dde0947222cb1700bc0537def4047b) adds the ability to turn the DC blocker off in non-linear phase mode and makes it use a linear phase DC blocker (at the expense of extra latency) in FIR mode. I hope this works for you.

**Comment by veksha** [comment]
thank you. it works!
