### ISSUE TITLE
Add a flat-top window?

### ISSUE THREAD

**Issue by endolith** [JoepVanlier/JSFX#3]
There are many to choose from:

https://github.com/scipy/scipy/issues/4234#issuecomment-243656820

**Comment by JoepVanlier** [comment]
I'd rather not include too many, as it may provide a choice overload, but I'm not opposed to adding a few from the flat top category.

Which ones would be the most relevant to have?

**Comment by endolith** [comment]
Yeah I just mean to pick one and include it. I'm not sure which one though. I have to read though that paper again.

**Comment by JoepVanlier** [comment]
Added the dantona5 flat-top in 4381c5939eecc6dc4cf0efe94da961dded5a85b1 :)

Thanks for the suggestion! Please reopen if you have issues with it.
