### ISSUE TITLE
Filther, overwriting font settings

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/JSFX#5]
It would be cool if Filther would not overwrite my font setting after each update. Thanks a lot. Otherwise, as always, perfect.

**Comment by JoepVanlier** [comment]
Which font settings?

**Comment by michaelsjackson** [comment]
Ok, it is not a setting, I meant the line in source code which sets the font, I guess we are not allowed to change it. I will change each time, no problem.

**Comment by JoepVanlier** [comment]
Ah okay. Maybe in the future I can split it out into an external file that you can edit! Right now, most of my focus is on getting this thing as controllable as possible. :)

**Comment by michaelsjackson** [comment]
Yeah, wonderful, nothing hurries, if I want a new font sooo much, I can always quickly edit it.

**Comment by michaelsjackson** [comment]
![JS: Filther  Saike Tools-Filther-MyFilther jsfx  - Track 1  15-15 _413](https://user-images.githubusercontent.com/5049512/55832175-31d51600-5b15-11e9-8a70-f6f5b3bccc61.png)
MyFilther.jsfx looks like this now. In case I want to use some older version with Atari ST fonts and background images, thanks Bri1 for the image, thanks Joep for all your magical codes.

**Comment by JoepVanlier** [comment]
I'm closing this issue as it should be pretty easy to change the font when needed.
