### ISSUE TITLE
Filther: At resonance noise > replace output with sample playback, some nice dusty noise

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/JSFX#6]
Just had following idea, not sure if that would be (easily) possible for Filther? One of the unwanted problems is kind of preventing that piiiiping, high tone resonance "noise" if you have too high or higher resonance values. I guess you understand what I mean.  Now the whole idea of this post is, which techniques could be used for preventing or better replacing those conditions, ok, this could be a checkbox, for those who want to keep the old behaviour.

It would need following:
a-  piiiping high tone noise detector
b-  replacing technique

I hope and guess a should be somehow possible. Now for b I had as best idea just replacing with sample playback (so sample could loop, if too short), I was thinking to something like dusty beautiful sounding noise, so you would kind of destroy your sound output, not by a high pitched piiiping tone, but in dust form, which sounds pleasing to the ear, if designed well. Flexibility of this approach would be anyone could set the sample they want. Not sure if anyone patented this idea, if not, maybe you could try, if you want?

unwanted condition  >  replacement technique

Applied to filters:
unwanted high pitched piiiping tone  >  sample playback (dusty beautiful sounding noise sound, something like the fog machine sound in clubs)

**Comment by JoepVanlier** [comment]
If you want less squealing, don't drive the resonance up so high. First filtering with a lot of resonance to then attempt to remove it again and replacing it with sample playback doesn't seem sensible to me. Sample playback is completely out of scope for this project. Besides, I'm out of sliders in this jsfx, so new features will not be added.

**Comment by michaelsjackson** [comment]
No problem I am trying something with drum replacement, if anything works, I can mention it here again.

**Comment by JoepVanlier** [comment]
Cool :)

When, one thing you could try if you want to get rid of that resonant peak, is to put a notch filter at exactly the same frequency to cut it again.
