### ISSUE TITLE
SpectrumAnalyzer button size changes, repositioning of buttons

### ISSUE THREAD

**Issue by JamesPeters667** [JoepVanlier/JSFX#8]
When using SpectrumAnalyzer at a size other than 3/4 of my screen (1080p), when clicking on some of the buttons along the top they may change size due to the differences in text string lengths ("mono" versus "mid/side" for instance). When this happens, the top row will sometimes spawn a second row with one or more button on the right side (sometimes far away from where it was before it was clicked, such as that "mono"/"mid/side" button). I thought some features were disappearing from time to time as a result. A suggestion: if the sizes of those button "boxes" could be fixed instead of variable, then they wouldn't reposition like that.

**Comment by JoepVanlier** [comment]
Should be fixed in 4.02 now :)

**Comment by JamesPeters667** [comment]
It seems good, thanks!

**Comment by JoepVanlier** [comment]
Closing the issue for now. If further issues arise, please feel free to reopen :)
