### ISSUE TITLE
MIDI Arp: Pattern doesn't reset on incoming MIDI notes

### ISSUE THREAD

**Issue by samlletas** [JoepVanlier/JSFX#86]
When selecting `MIDI` mode the pattern doesn't reset on incoming MIDI notes, it instead seems to behave like the `Free` mode where the pattern keeps continuously running and resets on playback.

Additionally, when closing and opening projects the mode always changes back to `Host`.

MIDI Arp v0.32
Reaper v6.81

**Comment by JoepVanlier** [comment]
Thanks for the report! Fixed in v0.33!

**Comment by samlletas** [comment]
Thanks for taking a look at this!

However I was not able to try the new version because ReaPack shows a 404 error when trying to update, I looked at the [index file](https://github.com/JoepVanlier/JSFX/commit/ece1e19c9588a5052767a6459debec3dd4896183) and the commit ID seems to point to a non existent commit: https://github.com/JoepVanlier/JSFX/commit/5989519d5e13880fe49fa56b6b34dd7147376a9d

Shouldn't that be https://github.com/JoepVanlier/JSFX/commit/767c93e4000752fac23a98c9abdb3001f97050ad instead?

**Comment by JoepVanlier** [comment]
It most certainly should. Sorry 'bout that. Must have run the indexer before I merged.

**Comment by samlletas** [comment]
Tried updating but still gives 404 errors 😅, looks like the 3 `jsfx-inc` files listed in v0.33 are still pointing to the non-existent https://github.com/JoepVanlier/JSFX/commit/5989519d5e13880fe49fa56b6b34dd7147376a9d commit:

https://github.com/JoepVanlier/JSFX/blob/ec6bb9330491491b561daf2b43d627d83df2dde5/index.xml#L5593
https://github.com/JoepVanlier/JSFX/blob/ec6bb9330491491b561daf2b43d627d83df2dde5/index.xml#L5594
https://github.com/JoepVanlier/JSFX/blob/ec6bb9330491491b561daf2b43d627d83df2dde5/index.xml#L5595

**Comment by JoepVanlier** [comment]
I ended up just bumping the version number, treating v0.34 as a botched release. I didn't want to rewrite history, since I pushed a few things after.

**Comment by samlletas** [comment]
v0.34 works perfectly, can confirm MIDI mode issue is fixed and selected mode is restored when reopening projects, thank you very much!

**Comment by JoepVanlier** [comment]
Cool! Thank you for the bug report and testing!

Closing the issue for now. Please don't hesitate to open another one if you run into further issues.
